qc:
  adapter1: AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG
  adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
  merge: false
  minqual: 20

minreads: 2

lanes:
  Pscabrum_GH1-4:
    combo: true
  Pscabrum_GH5-8:
    combo: true
  Pscabrum_SAf2012_1-4:
    combo: true
  Pscabrum_SAf2012_5-8:
    combo: true
